name: step
on:
  push:
    paths:
      - .github/workflows/step.yml
jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    steps:
      - name: Install pgvector
        run: |
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt-get install postgresql-14-pgvector
      - run: sudo systemctl start postgresql
      - run: sudo -u postgres psql -c 'CREATE EXTENSION vector'
  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-12, macos-11]
    steps:
      - name: Install pgvector
        run: brew install pgvector
      - run: brew services run postgresql@14 && sleep 1
      - run: psql -d postgres -c 'CREATE EXTENSION vector'
