name: step
on:
  push:
    paths:
      - .github/workflows/step.yml
jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            postgres: 16
          - os: ubuntu-22.04
            postgres: 14
          - os: ubuntu-20.04
            postgres: 14
    steps:
      - name: Install pgvector
        run: |
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt-get install postgresql-${{ matrix.postgres }}-pgvector
      - run: sudo systemctl start postgresql
      - run: sudo -u postgres psql -c 'CREATE EXTENSION vector'
  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-14, macos-13]
    steps:
      - run: brew install postgresql@17
      - run: brew link --overwrite postgresql@17
      - name: Install pgvector
        run: brew install pgvector
      - run: brew services start postgresql@17 && sleep 1
      - run: psql -d postgres -c 'CREATE EXTENSION vector'
  windows:
    runs-on: windows-latest
    steps:
      - name: Install pgvector
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd %TEMP%
          git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git
          cd pgvector
          nmake /NOLOGO /F Makefile.win
          nmake /NOLOGO /F Makefile.win install
        shell: cmd
      - run: sc config postgresql-x64-14 start=auto
      - run: net start postgresql-x64-14
      - run: |
          "%PGBIN%/psql" -d postgres -c "CREATE EXTENSION vector"
        shell: cmd
