name: windows
on:
  push:
    paths:
      - .github/workflows/step-windows.yml
jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            vs: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
          - os: windows-2019
            vs: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    steps:
      - name: Install pgvector
        run: |
          call "${{ matrix.vs }}\VC\Auxiliary\Build\vcvars64.bat"
          cd %TEMP%
          git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git
          cd pgvector
          nmake /NOLOGO /F Makefile.win
          nmake /NOLOGO /F Makefile.win install
        shell: cmd
      - run: sc config postgresql-x64-14 start=auto
      - run: net start postgresql-x64-14
      - run: |
          "%PGBIN%/psql" -d postgres -c "CREATE EXTENSION vector"
        shell: cmd
